/**
> Orthogonal intents (2026-08-20): helper generation conformance — golden
 * source shape, ordered candidates, argument validation, structured
 * candidate failures, and zero side effects.
 */

import { afterEach, describe, expect, it, vi } from "vitest";
import {
  generateUniPtyBackendManifestModule,
  UniPtyHelperCandidateError,
} from "../src/index.ts";
import { CONSUMER_ROOT } from "./setup.ts";

const SINGLE_CANDIDATE_SOURCE = `// @generated by @unipty/helper-backend — UniPty Backend manifest module.
// Hand-authorable bundler-neutral ESM (also valid TypeScript).
// Evaluation validates metadata without importing Backend entries,
// calling factories, or initializing native resources.
import { defineUniPtyBackendManifest } from "@unipty/backend";
import metadata0 from "@fixture/good-a/unipty.metadata";

export default defineUniPtyBackendManifest({
  entries: [
    {
      packageName: "@fixture/good-a",
      metadata: metadata0,
      load: () => import("@fixture/good-a"),
    },
  ],
});
`;

describe("generateUniPtyBackendManifestModule", () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("generates the golden single-candidate module source", async () => {
    const source = await generateUniPtyBackendManifestModule({
      candidates: ["@fixture/good-a"],
      from: CONSUMER_ROOT,
    });
    expect(source).toBe(SINGLE_CANDIDATE_SOURCE);
  });

  it("preserves candidate order across multiple candidates", async () => {
    const source = await generateUniPtyBackendManifestModule({
      candidates: ["@fixture/good-b", "@fixture/good-a"],
      from: CONSUMER_ROOT,
    });
    const firstMetadata = source.indexOf('import metadata0 from "@fixture/good-b');
    const secondMetadata = source.indexOf('import metadata1 from "@fixture/good-a');
    expect(firstMetadata).toBeGreaterThan(-1);
    expect(secondMetadata).toBeGreaterThan(firstMetadata);
    expect(source.indexOf('packageName: "@fixture/good-b"')).toBeLessThan(
      source.indexOf('packageName: "@fixture/good-a"'),
    );
    expect(source).toContain('load: () => import("@fixture/good-b")');
    expect(source).toContain('load: () => import("@fixture/good-a")');
  });

  it("uses the original specifier verbatim and embeds no physical paths", async () => {
    const source = await generateUniPtyBackendManifestModule({
      candidates: ["@fixture/good-a"],
      from: CONSUMER_ROOT,
    });
    expect(source).not.toContain("node_modules");
    expect(source).not.toContain("file://");
    expect(source).not.toContain(CONSUMER_ROOT);
    expect(source).not.toContain("schema: 1");
    expect(source).not.toContain("protocol");
  });

  it("requires an explicit from", async () => {
    await expect(
      generateUniPtyBackendManifestModule({
        candidates: ["@fixture/good-a"],
      } as unknown as { candidates: readonly string[]; from: URL | string }),
    ).rejects.toMatchObject({ code: "invalid-argument" });
  });

  it("rejects an empty candidate list", async () => {
    await expect(
      generateUniPtyBackendManifestModule({
        candidates: [],
        from: CONSUMER_ROOT,
      }),
    ).rejects.toMatchObject({ code: "invalid-argument" });
  });

  it("rejects duplicate candidates", async () => {
    await expect(
      generateUniPtyBackendManifestModule({
        candidates: ["@fixture/good-a", "@fixture/good-a"],
        from: CONSUMER_ROOT,
      }),
    ).rejects.toMatchObject({ code: "invalid-argument" });
  });

  it("throws a structured candidate error for an unresolvable candidate", async () => {
    const error = await generateUniPtyBackendManifestModule({
      candidates: ["@fixture/does-not-exist"],
      from: CONSUMER_ROOT,
    }).catch((caught: unknown) => caught);
    expect(error).toBeInstanceOf(UniPtyHelperCandidateError);
    const candidate = error as UniPtyHelperCandidateError;
    expect(candidate.code).toBe("candidate-unresolved");
    expect(candidate.packageName).toBe("@fixture/does-not-exist");
    expect(candidate.report).toMatchObject({
      status: "unresolved",
      reason: "missing",
    });
  });

  it("throws a structured candidate error for an incompatible candidate", async () => {
    const error = await generateUniPtyBackendManifestModule({
      candidates: ["@fixture/runtime-bun"],
      from: CONSUMER_ROOT,
    }).catch((caught: unknown) => caught);
    expect(error).toBeInstanceOf(UniPtyHelperCandidateError);
    const candidate = error as UniPtyHelperCandidateError;
    expect(candidate.code).toBe("candidate-incompatible");
    expect(candidate.packageName).toBe("@fixture/runtime-bun");
    expect(candidate.report.status).toBe("incompatible");
  });

  it("throws a structured candidate error for invalid metadata", async () => {
    const error = await generateUniPtyBackendManifestModule({
      candidates: ["@fixture/bad-metadata"],
      from: CONSUMER_ROOT,
    }).catch((caught: unknown) => caught);
    expect(error).toBeInstanceOf(UniPtyHelperCandidateError);
    expect((error as UniPtyHelperCandidateError).report.status).toBe(
      "metadata-invalid",
    );
  });

  it("writes no console output during generation", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    const log = vi.spyOn(console, "log").mockImplementation(() => {});
    const error = vi.spyOn(console, "error").mockImplementation(() => {});
    await generateUniPtyBackendManifestModule({
      candidates: ["@fixture/good-a"],
      from: CONSUMER_ROOT,
    });
    expect(warn).not.toHaveBeenCalled();
    expect(log).not.toHaveBeenCalled();
    expect(error).not.toHaveBeenCalled();
  });
});
